# Generated by Django 4.2.16 on 2024-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('pdf_solicitud', models.FileField(upload_to='pdf/solicitudes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
