# Generated by Django 4.2.16 on 2024-09-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_pedidoautorizacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/excel')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='formularios.obrasocial')),
            ],
        ),
    ]
