# Generated by Django 4.2.16 on 2024-09-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_categoriapersonal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaPersonal',
        ),
    ]
