# Generated by Django 4.2.16 on 2024-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_archivoexcelsubido'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='siglas',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
