# Generated by Django 4.2.16 on 2024-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_obrasocial_siglas_alter_obrasocial_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
