# Generated by Django 4.2.16 on 2024-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_archivoexcel_procesado_archivoexcel_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
